from dataclasses import dataclass
from typing import Protocol
@dataclass(frozen=True)
class ExecutionResult:
    ok:bool; provider:str; operation:str; external_id:str=''; evidence:dict|None=None; error:str=''
class PaymentProvider(Protocol):
    name:str
    def verify_incoming(self,event:dict)->ExecutionResult: ...
    def create_refund(self,payment_id:str,amount_eur:float)->ExecutionResult: ...
class ExchangeProvider(Protocol):
    name:str
    def market_snapshot(self,symbol:str)->dict: ...
    def place_order(self,symbol:str,side:str,quantity:float,limit_price:float|None=None)->ExecutionResult: ...
class MarketplaceProvider(Protocol):
    name:str
    def publish(self,offer:dict)->ExecutionResult: ...
    def fulfill(self,order:dict)->ExecutionResult: ...
